[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/notion/*"
  to = "/.netlify/functions/notion/:splat"
  status = 200

[[redirects]]
  from = "/writing/:slug"
  to = "/.netlify/functions/blog-render/:slug"
  status = 200
